### PR TITLE
Refactor Pytorch dataset 

### PR DESCRIPTION
**Pull request by jhamman**
**Description of proposed changes**

This PR introduces a number of changes to xbatcher's pytorch `MapDataset` class. These changes came out of the learnings while preparing [my AMS talk](https://ams.confex.com/ams/104ANNUAL/meetingapp.cgi/Paper/440043) (slides and blog post coming soon). The changes here allow for more control over how w

  - includes concurrent loading of x/y batches with dask.compute()
  - transforms now are expected to take an xarray object and return a torch.Tensor

### CODE REVIEW

**Comment by maxrjones** [comment]
Thanks for contributing these improvements @jhamman! I'll have time to review on Thursday. It would be good to hit the test coverage target, so do you mind if I push additional tests as part of the review?

**Comment by maxrjones** [comment]
Sorry that I did not have time to review this yet! I am about to head out of office but would be glad to work on this with you after returning on March 5, or would welcome other reviewers in the meantime.

**Comment by andersy005** [comment]
pre-commit.ci autofix

**Comment by andersy005** [comment]
@jhamman, i pushed additional tests/fixes to your branch.. i hope you don';t mind :) 

@maxrjones, curious to hear your feedback on this before I merge it into main when you get a chance

**Review by andersy005 — APPROVED** [review]

**Comment by maxrjones** [comment]
@weiji14 would you have any interest in reviewing this PR? I can if you don't have time or interest, I just expect that your expertise would be particularly beneficial on the PyTorch dataset revisions. It'd also be helpful to know if we need to expect downstream implications for zen3geo.

**Comment by weiji14** [comment]
I'll be travelling most of the next two weeks (about to head to the airport actually), so probably won't get to this until September. If you can do the review @maxrjones, that would be great!

**Comment by maxrjones** [comment]
> I'll be travelling most of the next two weeks (about to head to the airport actually), so probably won't get to this until September. If you can do the review @maxrjones, that would be great!

Sounds good, safe travels! @andersy005 I'll block some time to look at this on Friday.

**Comment by andersy005** [comment]
this can definitely wait. so, no rush/worries @maxrjones

**Comment by andersy005** [comment]
i spoke with @maxrjones earlier this week and it's my understanding that we can merge this as-is and cut a new release, making the updated feature available to users. we can revisit any potential issues or missing elements if needed.

@jhamman, thank you for putting this together!

**Pull request merged**
